import java.util.Scanner;
/**
*Computes the value generated by an expression.
*
* Project 3
*@author Patrick Spafford COMP 1210- 010
*@version 9-10-2-18
*/
public class FormulaEval {
/**.
*Performs the operation and prints result
*@param args not used
*/
   public static void main(String [] args) { // Executes program
      double x, result, absoluteValue, denominator;
      Scanner userInput = new Scanner(System.in);
      System.out.print("Enter a value for x: ");
      x = userInput.nextDouble();
      
      absoluteValue = Math.abs(3.9 * Math.pow(x, 5) - Math.pow(x, 3) + 1);
      denominator = (1.6 * Math.pow(x, 2) + 2.7 * x + 3.8);
      result = (1000 * x + Math.sqrt(absoluteValue)) / denominator;
      System.out.println("Result: " + result);
      
      String resultString = Double.toString(result);
      int periodPosition = resultString.indexOf(".");
      int rightOfDecimal, leftOfDecimal;
      rightOfDecimal = resultString.length() - periodPosition - 1;
      leftOfDecimal = resultString.length() - rightOfDecimal - 1;
      System.out.println("# of characters to left of decimal point: "
         + leftOfDecimal); 
      System.out.println("# of characters to right of decimal point: "
         + rightOfDecimal);
      
      java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0.0####"); 
      System.out.println("Formatted Result: "
         + df.format(result));
   }

}